# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicpro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singup',
            new_name='Signup',
        ),
    ]
