# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicpro', '0002_auto_20180910_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicpro.ContactNumber'),
        ),
    ]
